//tag::about[]

== DataHandwerk documentation

documentation for these projects:

* https://github.com/DataHandwerk/DataHandwerk-toolkit-mssql

=== Why we don't use github wiki and github pages?

insted of markdown we use https://asciidoc.org/[asciidoc]

* https://en.wikipedia.org/wiki/AsciiDoc
* https://asciidoctor.org[Asciidoctor]
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/


github has asciidoc support out of the box, but githup doesn't support all features, and it has no asciidoctor. Some missing features:

* inline documents
* inline graphics

That's why we need other ways to publish documentation.

* maybe https://antora.org/ could be used, but maybe it would be oversized
* https://github.com/docToolchain/docToolchain is great and easy to use to generate HTML (or PDF, or other documents) from asciidoc files
* doctoolchain developers also provide a template, how to create a documentation website which can be easy hosted for example on https://www.netlify.com/ +
and this repository is used as template for the current project: https://github.com/docToolchain/arc42-template-project

//end::about[]


== arc42 Project Template

This is a template for a Java/arc42 documentation project.

A demo for the deployed microsite of the documentation template can be found at https://arc42-demo.netlify.app/

=== Tech-Stack

This repository was build was with/uses the following technology stack.

Groovy is only optional for demonstration purpose.
It show how to mix a Hello-World app with documentation in one Repository.

[cols="2"]
|===
| Gradle
| 6.7.1

| JVM
| 15.0.1 (Oracle Corporation 15.0.1+9-18)

| jBake
| 2.6.5

| twitter-bootstrap
| 5.0.0-beta

| arc42
| 7.0DE

| Groovy
| 2.5.12
|===


=== How to build

use `./gradlew bake` to build the site and `./gradlew bakePreview` to start a little webserver.
